apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-external-secrets
  annotations:
    policies.kyverno.io/title: Enforce External Secrets Operator
    policies.kyverno.io/category: Multi-Tenancy / Security
    policies.kyverno.io/description: >-
      Creating raw secrets is explicitly prohibited to prevent credential leaks.
      All secrets must be managed through the ExternalSecrets operator.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: block-raw-secrets
      match:
        any:
          - resources:
              kinds:
                - Secret
              namespaces:
                - k8s-node-app
      exclude:
        any:
          - clusterRoles:
              - cluster-admin
          - subjects:
              - kind: ServiceAccount
                name: external-secrets-operator
      validate:
        message: "Stop! Creating manual Secrets in 'k8s-node-app' is forbidden. You must create an 'ExternalSecret' custom resource instead."
        deny:
          conditions:
            any:
              - key: "{{ request.operation }}"
                operator: Equals
                value: CREATE