variable "environment" { type = string }
variable "cluster_name" { type = string }
variable "cluster_version" {
  type    = string
  default = "1.30"
}
variable "vpc_id" { type = string }
variable "private_subnet_ids" { type = list(string) }

# Переменные скалирования
variable "node_min_size" { type = number }
variable "node_max_size" { type = number }
variable "node_desired_size" { type = number }
variable "instance_types" { type = list(string) }
variable "capacity_type" { type = string }

variable "node_group_role_arn" {
  type        = string
  description = "The IAM role ARN generated by the IAM module for the worker nodes"
}