apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager-store
  namespace: k8s-node-app
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-node-app-secrets
  namespace: k8s-node-app
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: SecretStore
  target:
    name: k8s-node-app-live-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: dev/k8s-node-app/secrets
        property: db_url
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: dev/k8s-node-app/secrets
        property: jwt_key